### ISSUE TITLE
This no longer works with the new Datadog Agent

### ISSUE THREAD

**Issue by bradleyess** [bithauschile/datadog-ga#6]
I'd love to get this working in our system, but have lots of trouble.

The error I get when checking 

```
Error: could not load ga:
* JMX Check Loader: check is not a jmx check, or unable to determine if it's so
* Python Check Loader: ['Traceback (most recent call last):\n', '  File "/etc/datadog-agent/checks.d/ga.py", line 12, in <module>\n    from oauth2client import tools\n', '  File "/home/ubuntu/.local/lib/python2.7/site-packages/oauth2client/tools.py", line 99, in <module>\n    argparser = _CreateArgumentParser()\n', '  File "/home/ubuntu/.local/lib/python2.7/site-packages/oauth2client/tools.py", line 82, in _CreateArgumentParser\n    parser = argparse.ArgumentParser(add_help=False)\n', '  File "/opt/datadog-agent/embedded/lib/python2.7/argparse.py", line 1586, in __init__\n prog = _os.path.basename(_sys.argv[0])\n', "AttributeError: 'module' object has no attribute 'argv'\n"]
* Core Check Loader: Check ga not found in Catalog
Error: no valid check found
```

**Comment by whazenberg** [comment]
Please have a look at PR #8.
