### ISSUE TITLE
no module named oauth2client.service_account

### ISSUE THREAD

**Issue by betodevops** [bithauschile/datadog-ga#7]
python3 /etc/datadog-agent/checks.d/ga.py
Traceback (most recent call last):
  File "/etc/datadog-agent/checks.d/ga.py", line 17, in <module>
    from checks import AgentCheck, CheckException
ImportError: No module named 'checks'
root@ip-10-30-63-46:/etc/datadog-agent/conf.d# datadog-agent check ga

Error: could not load ga:
* JMX Check Loader: check is not a jmx check, or unable to determine if it's so
* Python Check Loader: ['Traceback (most recent call last):\n', '  File "/etc/datadog-agent/checks.d/ga.py", line 20, in <module>\n    from oauth2client.service_account import ServiceAccountCredentials\n', 'ImportError: No module named oauth2client.service_account\n']
* Core Check Loader: Check ga not found in Catalog
Error: no valid check found
Usage:
  agent check <check_name> [flags]

Flags:
  -r, --check-rate         check rates by running the check twice
  -d, --delay int          delay between running the check and grabbing the metrics in miliseconds (default 100)
  -h, --help               help for check
  -l, --log-level string   set the log level (default 'off')

Global Flags:
  -c, --cfgpath string   path to directory containing datadog.yaml
  -n, --no-color         disable color output

**Comment by jmakuc** [comment]
Hi beto

Unfortunately, this check was written for an old version of the agent. I'm trying to find some time to update it so it will run on Agent 6. 

If you would like to help, you are very welcome!

**Comment by whazenberg** [comment]
Hi,

The library oauth2client is deprecated, [ref](https://github.com/googleapis/oauth2client).

Please check out PR #8.

-Wytze
